### ISSUE TITLE
ModuleNotFoundError: No module named 'cg-noisetools.renoise_calculation'

### ISSUE THREAD

**Issue by 925-Studio** [chrisgoringe/cg-noisetools#1]
Can't import this custom_nodes after updated to the latest version, and below error info appears in terminal:

```
Traceback (most recent call last):
  File "/home/silver/Playground/AI/ComfyUI/nodes.py", line 2072, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/silver/Playground/AI/ComfyUI/custom_nodes/cg-noisetools/__init__.py", line 3, in <module>
    from .renoise_calculation import SplitSigmasWithRewind
ModuleNotFoundError: No module named 'cg-noisetools.renoise_calculation'

Cannot import /home/silver/Playground/AI/ComfyUI/custom_nodes/cg-noisetools module for custom nodes: No module named 'cg-noisetools.renoise_calculation'
```

Can you look into this, please? Thanks in advance.

**Comment by chrisgoringe** [comment]
Try now

**Comment by 925-Studio** [comment]
Fixed! Thanks a lot.
